import React from 'react';
import {AppRegistry} from 'react-native';
import CodeReloadHost from './CodeReloadHost';
import {registerBuiltin} from './runtime/moduleRegistry';
import type {AiModel} from './ai/models';

declare const __DEV__: boolean;

export interface RegisterCodeReloadOptions {
  /// Build-time snapshot of the app source (path -> contents), generated by the
  /// `code-reload-snapshot` script. Required for on-device live editing.
  sources?: Record<string, string>;
  /// Entry module for the interpreter. Defaults to `index`.
  entry?: string;
  /// AI credentials/model for the native agent.
  apiKey?: string;
  model?: AiModel;
  /// Extra modules edited code may import (name -> module), beyond
  /// `react`/`react-native`.
  builtins?: Record<string, any>;
}

/// 1:1 swap for `AppRegistry.registerComponent(appName, () => App)`.
///
/// In development it mounts the CodeReload root (on-device interpreter + editor +
/// agent) with the real `App` as a fallback. In release it registers the
/// real `App` directly, so nothing routes through CodeReload.
export function registerCodeReloadApp(
  appName: string,
  App: React.ComponentType<any>,
  opts: RegisterCodeReloadOptions = {},
) {
  if (typeof __DEV__ !== 'undefined' && __DEV__) {
    if (opts.builtins) {
      for (const [name, mod] of Object.entries(opts.builtins)) {
        registerBuiltin(name, mod);
      }
    }
    const Root = () => (
      <CodeReloadHost
        sources={opts.sources ?? {}}
        entry={opts.entry ?? 'index'}
        apiKey={opts.apiKey}
        model={opts.model}
        fallback={App}
      />
    );
    AppRegistry.registerComponent(appName, () => Root);
  } else {
    AppRegistry.registerComponent(appName, () => App);
  }
}
